name: Update videos.json
on:
  schedule:
    - cron: "*/30 12-22 * * 1-5"   # every 30 min, 8am–6pm ET, Mon–Fri (UTC times)
  workflow_dispatch: {}             # manual "Run workflow" button

permissions:
  contents: write                   # allow this workflow to push commits

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch API → videos.json.tmp
        run: |
          set -euo pipefail
          curl -fsSL "$API_URL" -o videos.json.tmp

      - name: Validate JSON and stamp timestamp
        run: |
          node -e "JSON.parse(require('fs').readFileSync('videos.json.tmp','utf8'))"
          node -e "const fs=require('fs');const j=JSON.parse(fs.readFileSync('videos.json.tmp','utf8'));j.generated_at=new Date().toISOString();fs.writeFileSync('videos.json.tmp',JSON.stringify(j,null,2));"

      - name: Commit only if changed
        run: |
          if ! cmp -s videos.json.tmp videos.json 2>/dev/null; then
            mv videos.json.tmp videos.json
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add videos.json
            git commit -m "chore: refresh videos.json"
            git push
          else
            echo "No changes."
          fi
        shell: bash
    env:
      API_URL: "https://script.google.com/macros/s/AKfycbx5911lrXGR7GuSHQ-esRJH68v4q-nYzrLjgGQC5hZiDoN8ZhOJ1BieWeWhiJDiWukP/exec"
